### ISSUE TITLE
addon broken

### ISSUE THREAD

**Issue by kec2** [xbmc-danish-addons/plugin.video.gamereactor.dk#1]
Hi,

This addon no longer works.
It display a list of topics like, Interview, Preview, Programmer etc. But all topics are empty.

Regards Klaus

Some log:
12:49:30 T:140352333797120  NOTICE: -->Python Interpreter Initialized<--
12:49:30 T:140352333797120   DEBUG: CPythonInvoker(18, /storage/.xbmc/addons/plugin.video.gamereactor.dk/addon.py): the source file to load is /storage/.xbmc/addons/plugin.video.gamereactor.dk/addon.py
12:49:30 T:140352333797120   DEBUG: CPythonInvoker(18, /storage/.xbmc/addons/plugin.video.gamereactor.dk/addon.py): setting the Python path to /storage/.xbmc/addons/plugin.video.gamereactor.dk:/storage/.xbmc/addons/script.module.pyamf/lib:/storage/.xbmc/addons/script.module.chardet/lib:/storage/.xbmc/addons/script.module.simplejson/lib:/storage/.xbmc/addons/script.module.beautifulsoup/lib:/usr/share/xbmc/addons/script.module.pil/lib:/storage/.xbmc/addons/script.common.plugin.cache/lib:/storage/.xbmc/addons/script.module.simple.downloader/lib:/storage/.xbmc/addons/script.module.buggalo/lib:/usr/share/xbmc/addons/xbmc.debug/:/storage/.xbmc/addons/script.module.parsedom/lib:/storage/.xbmc/addons/script.module.xbmcswift2/lib:/storage/.xbmc/addons/script.module.requests2/lib:/storage/.xbmc/addons/script.module.elementtree/lib:/storage/.xbmc/addons/script.module.feedparser/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/PIL:/usr/lib/python2.7/site-packages/gtk-2.0
12:49:30 T:140352333797120   DEBUG: CPythonInvoker(18, /storage/.xbmc/addons/plugin.video.gamereactor.dk/addon.py): entering source directory /storage/.xbmc/addons/plugin.video.gamereactor.dk
12:49:30 T:140352333797120   DEBUG: CPythonInvoker(18, /storage/.xbmc/addons/plugin.video.gamereactor.dk/addon.py): instantiating addon using automatically obtained id of "plugin.video.gamereactor.dk" dependent on version 2.1.0 of the xbmc.python api
12:49:31 T:140352333797120   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 400: Bad request
                                            Traceback (most recent call last):
                                              File "/storage/.xbmc/addons/plugin.video.gamereactor.dk/addon.py", line 90, in <module>
                                                grtv.showCategory(PARAMS['slug'][0])
                                              File "/storage/.xbmc/addons/plugin.video.gamereactor.dk/addon.py", line 34, in showCategory
                                                html = self._downloadUrl(GRTV_URL + 'list_20latest.php?l=' + slug)
                                              File "/storage/.xbmc/addons/plugin.video.gamereactor.dk/addon.py", line 71, in _downloadUrl
                                                u = urllib2.urlopen(r)
                                              File "/home/stephan/projects/openelec-4.0/build.OpenELEC-Generic.x86_64-4.0.7/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 126, in urlopen
                                              File "/home/stephan/projects/openelec-4.0/build.OpenELEC-Generic.x86_64-4.0.7/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 406, in open
                                              File "/home/stephan/projects/openelec-4.0/build.OpenELEC-Generic.x86_64-4.0.7/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 519, in http_response
                                              File "/home/stephan/projects/openelec-4.0/build.OpenELEC-Generic.x86_64-4.0.7/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 444, in error
                                              File "/home/stephan/projects/openelec-4.0/build.OpenELEC-Generic.x86_64-4.0.7/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
                                              File "/home/stephan/projects/openelec-4.0/build.OpenELEC-Generic.x86_64-4.0.7/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
                                            HTTPError: HTTP Error 400: Bad request
                                            -->End of Python script error report<--
12:49:31 T:140353763071808   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
12:49:31 T:140352333797120    INFO: Python script stopped
12:49:31 T:140352333797120   DEBUG: Thread LanguageInvoker 140352333797120 terminating
12:49:31 T:140352979707648   DEBUG:  WaitOnScriptResult - plugin exited prematurely - terminating
12:49:31 T:140353763071808   ERROR: GetDirectory - Error getting plugin://plugin.video.gamereactor.dk/?slug=GRTV%20News
12:49:31 T:140353763071808   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.gamereactor.dk/?slug=GRTV%20News) failed
12:49:31 T:140353763071808   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.gamereactor.dk/)
12:49:31 T:140353763071808   DEBUG:   ParentPath = [addons://sources/video/]
12:49:31 T:140353763071808   DEBUG: Loading items: 20, directory: plugin://plugin.video.gamereactor.dk/ sort method: 0, ascending: false
12:49:31 T:140352333797120  NOTICE: Thread BackgroundLoader start, auto delete: false
12:49:31 T:140352333797120   DEBUG: Thread BackgroundLoader 140352333797120 terminating

**Comment by twinther** [comment]
It works for me right now, even the GRTV News category you tried.

**Comment by kec2** [comment]
The version of this addon that I can install in OpenElec (4.0.7) is 1.0.1.
I see that the latest version here is 2.0.0.
I uninstallet 1.0.1. 
Downloaded and installed 2.0.0. 
The result is that it works greate. It loads videos very fast.

And I'm happy.

**Comment by twinther** [comment]
Ah yes, it hasn't been updated in the official repo, I must have forgotten about it. Thanks.
